Rb tabbed interface
AnnaVi11arrea1/photogram-industrial pull request #8
Opened 2024-10-22 15:47 UTC by AnnaVi11arrea1

2024-10-25 17:22 UTC, armstrca requested changes
"Liked photos" needs to match the layout of Users#show

2024-10-25 17:26 UTC, armstrca requested changes

2024-10-25 17:26 UTC, armstrca commented on app/views/users/show.html.erb
Line 2 should be:

```
<div class="col-md-6 offset-3">
```

2024-10-25 17:26 UTC, armstrca commented on app/views/likes/likes.html.erb
Line 2 should be:

```
<div class="col-md-6 offset-3">
```

2024-10-25 20:50 UTC, AnnaVi11arrea1 commented on app/views/likes/likes.html.erb
done

2024-10-25 20:51 UTC, AnnaVi11arrea1 commented on app/views/users/show.html.erb
done!

2024-10-25 21:09 UTC, viviancreates commented
Looks good, great job implementing changes requested

2024-10-28 14:50 UTC, armstrca requested changes

2024-10-28 14:50 UTC, armstrca commented on app/views/users/likes.html.erb
This view is kinda broken:

![Screenshot 2024-10-28 094723](https://github.com/user-attachments/assets/8014cd22-9d2f-48f8-b68a-9aec3a9d0d9b)

2024-10-29 16:18 UTC, AnnaVi11arrea1 commented on app/views/users/likes.html.erb
Changes made to likes view

2024-11-01 21:50 UTC, armstrca approved these changes
![d4798a46f283496f96a831800feff102 1](https://github.com/user-attachments/assets/5161def4-1001-4769-b7c5-fe4be5151770)

2024-11-04 22:14 UTC, merged